name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.0' 

      - run: go mod tidy

      - run: go fmt ./...

      - run: git diff-index -p HEAD --

      - run: mkdir release-bin/

      - run: env GOOS=linux GOARCH=amd64 go build -o release-bin/deditool-linux-amd64

      - run: env GOOS=linux GOARCH=arm64 go build -o release-bin/deditool-linux-arm64

      - run: env GOOS=windows GOARCH=amd64 go build -o release-bin/deditool-win-amd64.exe

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: |
            LICENSE
            release-bin/*
